--Each entry in the table has 2 values:
-- 1 The name of the instance.
-- 2 The name to display of the instance

displayInstanceName = {
	{"Scarlet Monastery", "Scarlet Monastery"},
	{"Scarlet Halls", "Scarlet Halls"},
	{"Scholomance", "Scholomance"},
	{"Shadowfang Keep", "Shadowfang Keep"},
	{"Ragefire Chasm", "Ragefire Chasm"},
	{"Deadmines", "Deadmines"},
	{"Stormwind Stockade", "Stormwind Stockade"},
	{"Blackfathom Deeps", "Blackfathom Deeps"},
	{"Gnomeregan", "Gnomeregan"},
	{"Razorfen Kraul", "Razorfen Kraul"},
	{"Razorfen Downs", "Razorfen Downs"},
	{"Uldaman", "Uldaman"},
	{"Zul'Farrak", "Zul'Farrak"},
	{"Sunken Temple", "Sunken Temple"},
	{"Maraudon", "Maraudon"},
	{"Blackrock Depths", "Blackrock Depths"},
	{"Lower Blackrock Spire", "Lower Blackrock Spire"},
	{"Dire Maul", "Dire Maul"},
	{"Hellfire Citadel: The Blood Furnace", "The Blood Furnace"},
	{"Hellfire Citadel: Ramparts", "Hellfire Ramparts"},
	{"Hellfire Citadel: The Shattered Halls", "The Shattered Halls"},
	{"Coilfang: The Slave Pens", "Slave Pens"},
	{"Coilfang: The Steamvault", "Steamvault"},
	{"Coilfang: The Underbog", "Underbog"},
	{"Tempest Keep: The Botanica", "The Botanica"},
	{"Tempest Keep: The Mechanar", "The Mechanar"},
	{"Tempest Keep: The Arcatraz", "The Arcatraz"},
	{"Auchindoun: Auchenai Crypts", "Auchenai Crypts"},
	{"Auchindoun: Mana-Tombs", "Mana-Tombs"},
	{"Auchindoun: Sethekk Halls", "Sethekk Halls"},
	{"Auchindoun: Shadow Labyrinth", "Shadow Labyrinth"},
	{"Magisters' Terrace", "Magisters' Terrace"},
	{"Opening of the Dark Portal", "The Black Morrass"},
	{"The Escape from Durnholde", "Old Hillsbrad Foothills"},
	{"Pit of Saron", "Pit of Saron"},
	{"The Forge of Souls", "Forge of Souls"},
	{"Halls of Reflection", "Halls of Reflection"},
	{"The Nexus", "The Nexus"},
	{"Auchindoun", "Auchindoun"},
}