--Each entry in the table has 3 values:
-- 1 The name of the dungeon.
-- 2 The name of the Elite
-- 3 A number indicating the amount of that Elite there is in the dungeon.

dungeonEliteArray = {
{"Scarlet Monastery", "Scarlet Centurion", 12},
{"Scarlet Monastery", "Scarlet Fanatic", 22},
{"Scarlet Monastery", "Scarlet Flamethrower", 6},
{"Scarlet Monastery", "Scarlet Judicator", 12},
{"Scarlet Monastery", "Scarlet Purifier", 20},
{"Scarlet Monastery", "Fallen Crusader", 5},
{"Scarlet Monastery", "Scarlet Zealot", 13},
{"Scarlet Halls", "Angry Hound", 8},
{"Scarlet Halls", "Starving Hound", 20},
{"Scarlet Halls", "Commander Lindon", 1},
{"Scarlet Halls", "Scarlet Evangelist", 4},
{"Scarlet Halls", "Scarlet Evoker", 2},
{"Scarlet Halls", "Scarlet Hall Guardian", 4},
{"Scarlet Halls", "Scarlet Myrmidon", 3},
{"Scarlet Halls", "Scarlet Scholar", 2},
{"Scarlet Halls", "Scarlet Scourge Hewer", 4},
{"Scarlet Halls", "Scarlet Treasurer", 5},
{"Scarlet Halls", "Vigilant Watchman", 5},
{"Scholomance", "Boneweaver", 6},
{"Scholomance", "Bored Student", 28},
{"Scholomance", "Candlestick Mage", 5},
{"Scholomance", "Flesh Horror", 3},
{"Scholomance", "Krastinovian Carver", 16},
{"Scholomance", "Professor Slate", 1},
{"Scholomance", "Risen Guard", 5},
{"Scholomance", "Scholomance Acolyte", 12},
{"Scholomance", "Scholomance Neophyte", 13},
{"Scholomance", "Bound Servant", 4},
{"Scholomance", "Soul Fragment", 24},
{"Shadowfang Keep", "Corpse Eater", 8},
{"Shadowfang Keep", "Dread Scryer", 2},
{"Shadowfang Keep", "Fetid Ghoul", 3},
{"Shadowfang Keep", "Ghostly Cook", 4},
{"Shadowfang Keep", "Haunted Servitor", 13},
{"Shadowfang Keep", "Mindless Horror", 4},
{"Shadowfang Keep", "Pustulant Monstrosity", 2},
{"Shadowfang Keep", "Shadowy Attendant", 10},
{"Shadowfang Keep", "Sorcerous Skeleton", 3},
{"Shadowfang Keep", "Spitebone Flayer", 2},
{"Shadowfang Keep", "Spitebone Guardian", 2},
{"Shadowfang Keep", "Spitebone Skeleton", 4},
{"Shadowfang Keep", "Stone Sleeper", 4},
{"Shadowfang Keep", "Tormented Officer", 2},
{"Shadowfang Keep", "Unstable Ravager", 3},
{"Shadowfang Keep", "Wailing Guardsman", 11},
{"Auchindoun", "Auchenai Arbiter", 1},
{"Auchindoun", "Auchenai Defender", 2},
{"Auchindoun", "Auchenai Magus", 1},
{"Auchindoun", "Auchenai Warden", 1},
{"Auchindoun", "Auchenai Zealot", 1},
{"Auchindoun", "Cackling Pyromaniac", 13},
{"Auchindoun", "Felborne Abyssal", 1},
{"Auchindoun", "Felguard", 4},
{"Auchindoun", "Sargerei Arbiter", 2},
{"Auchindoun", "Sargerei Cleric", 1},
{"Auchindoun", "Sargerei Defender", 7},
{"Auchindoun", "Sargerei Hoplite", 2},
{"Auchindoun", "Sargerei Magus", 2},
{"Auchindoun", "Sargerei Ritualist", 3},
{"Auchindoun", "Sargerei Soulbinder", 1},
{"Auchindoun", "Sargerei Soulpriest", 1},
{"Auchindoun", "Sargerei Spirit-Tender", 1},
{"Auchindoun", "Sargerei Warden", 1},
{"Auchindoun", "Sargerei Zealot", 3},
{"Auchindoun", "Zar'shuul", 1},
{"Auchindoun", "Durag the Dominator", 1},
{"Auchindoun", "Gul'Kosh", 1},
{"Auchindoun", "Grom'tash the Destructor", 1},
{"Ragefire Chasm", "Adolescent Flame Hound", 9},
{"Ragefire Chasm", "Corrupted Flamecaller", 5},
{"Ragefire Chasm", "Corrupted Houndmaster", 5},
{"Ragefire Chasm", "Corrupted Reaver", 14},
{"Ragefire Chasm", "Dark Shaman Acolyte", 9},
{"Ragefire Chasm", "Dark Shaman Researcher", 7},
{"Ragefire Chasm", "Mature Flame Hound", 9},
{"Wailing Caverns", "Deviate Adder", 14},
{"Wailing Caverns", "Deviate Dreadfang", 4},
{"Wailing Caverns", "Deviate Guardian", 18},
{"Wailing Caverns", "Deviate Lasher", 22},
{"Wailing Caverns", "Deviate Moccasin", 6},
{"Wailing Caverns", "Deviate Ravager", 34},
{"Wailing Caverns", "Deviate Shambler", 14},
{"Wailing Caverns", "Deviate Venomwing", 6},
{"Wailing Caverns", "Deviate Viper", 16},
{"Wailing Caverns", "Druid of the Fang", 42},
{"Wailing Caverns", "Evolving Ectoplasm", 10},
{"Deadmines", "Defias Blood Wizard", 4},
{"Deadmines", "Defias Enforcer", 6},
{"Deadmines", "Defias Envoker", 3},
{"Deadmines", "Defias Overseer", 2},
{"Deadmines", "Defias Pirate", 23},
{"Deadmines", "Defias Reaper", 2},
{"Deadmines", "Defias Shadowguard", 5},
{"Deadmines", "Defias Squallshaper", 10},
{"Deadmines", "Defias Watcher", 2},
{"Deadmines", "Foe Reaper 5000", 1},
{"Deadmines", "Glubtok", 1},
{"Deadmines", "Helix Gearbreaker", 1},
{"Deadmines", "Lumbering Oaf", 1},
{"Deadmines", "Mine Bunny", 2},
{"Deadmines", "Oaf Lackey", 6},
{"Deadmines", "Ogre Bodyguard", 2},
{"Deadmines", "Ogre Henchman", 5},
{"Stormwind Stockade", "Enraged Fire Elemental", 9},
{"Stormwind Stockade", "Riverpaw Basher", 5},
{"Stormwind Stockade", "Riverpaw Looter", 6},
{"Stormwind Stockade", "Riverpaw Poacher", 7},
{"Stormwind Stockade", "Riverpaw Shaman", 6},
{"Stormwind Stockade", "Riverpaw Slayer", 9},
{"Stormwind Stockade", "Rowdy Troublemaker", 4},
{"Stormwind Stockade", "Searing Destroyer", 6},
{"Stormwind Stockade", "Shifty Thief", 8},
{"Stormwind Stockade", "Slag Fury", 6},
{"Stormwind Stockade", "Vicious Thug", 3},
{"Blackfathom Deeps", "Aku'mai the Devourer", 1},
{"Blackfathom Deeps", "Blindlight Bilefin", 9},
{"Blackfathom Deeps", "Blindlight Murloc", 24},
{"Blackfathom Deeps", "Blindlight Rotmouth", 1},
{"Blackfathom Deeps", "Deep Terror", 10},
{"Blackfathom Deeps", "Executioner Gore", 1},
{"Blackfathom Deeps", "Ghamoo-Ra", 1},
{"Blackfathom Deeps", "Guardian of the Deep", 1},
{"Blackfathom Deeps", "Pahboo-Ra", 1},
{"Blackfathom Deeps", "Razorshell Snapjaw", 3},
{"Blackfathom Deeps", "Twilight Aquamancer", 7},
{"Blackfathom Deeps", "Twilight Disciple", 22},
{"Blackfathom Deeps", "Twilight Shadow", 6},
{"Blackfathom Deeps", "Twilight Shadowmage", 4},
{"Blackfathom Deeps", "Twilight Storm Mender", 8},
{"Blackfathom Deeps", "Twilight Tormentor", 2},
{"Gnomeregan", "Caverndeep Burrower", 26},
{"Gnomeregan", "Caverndeep Reaver", 10},
{"Gnomeregan", "Corrosive Lurker", 3},
{"Gnomeregan", "Dark Iron Agent", 24},
{"Gnomeregan", "Irradiated Horror", 5},
{"Gnomeregan", "Irradiated Pillager", 24},
{"Gnomeregan", "Irradiated Slime", 5},
{"Gnomeregan", "Leprous Defender", 11},
{"Gnomeregan", "Mechanized Guardian", 8},
{"Gnomeregan", "Mechanized Sentry", 18},
{"Gnomeregan", "Mechano-Flamewalker", 7},
{"Gnomeregan", "Mechano-Frostwalker", 3},
{"Gnomeregan", "Mechano-Tank", 4},
{"Gnomeregan", "Peacekeeper Security Suit", 6},
{"Razorfen Kraul", "Aggem Thorncurse", 1},
{"Razorfen Kraul", "Battle Boar", 12},
{"Razorfen Kraul", "Blood-Branded Razorfen", 4},
{"Razorfen Kraul", "Cave Bat", 4},
{"Razorfen Kraul", "Death Speaker Jargba", 1},
{"Razorfen Kraul", "Enormous Bullfrog", 1},
{"Razorfen Kraul", "Grotto Toad", 7},
{"Razorfen Kraul", "Groyat, the Blind Hunter", 1},
{"Razorfen Kraul", "Kraulshaped Monstrosity", 1},
{"Razorfen Kraul", "Kraulshaper Tukaar", 1},
{"Razorfen Kraul", "Razorfen Beast Stalker", 12},
{"Razorfen Kraul", "Razorfen Geomagus", 2},
{"Razorfen Kraul", "Razorfen Hidecrusher", 2},
{"Razorfen Kraul", "Razorfen Huntmaster", 12},
{"Razorfen Kraul", "Razorfen Kraulshaper", 7},
{"Razorfen Kraul", "Razorfen Scarblade", 3},
{"Razorfen Kraul", "Razorfen Stonechanter", 3},
{"Razorfen Kraul", "Razorfen Thornbolt", 2},
{"Razorfen Kraul", "Roogug", 1},
{"Razorfen Downs", "Boneflayer Ghoul", 9},
{"Razorfen Downs", "Bubonic Geist", 9},
{"Razorfen Downs", "Death's Head Arachnomancer", 4},
{"Razorfen Downs", "Death's Head Ghoul Wrangler", 3},
{"Razorfen Downs", "Death's Head Necrolyte", 7},
{"Razorfen Downs", "Death's Head Shadowmender", 7},
{"Razorfen Downs", "Freezing Spirit", 2},
{"Razorfen Downs", "Frozen Soul", 4},
{"Razorfen Downs", "Plague-Rotted Webslinger", 7},
{"Razorfen Downs", "Splinterbone Captain", 2},
{"Razorfen Downs", "Thorn Eater Ghoul", 4},
{"Uldaman", "Jadespine Basilisk", 3},
{"Uldaman", "Shadowforge Darkcaster", 2},
{"Uldaman", "Shadowforge Geologist", 3},
{"Uldaman", "Shadowforge Relic Hunter", 5},
{"Uldaman", "Shadowforge Sharpshooter", 2},
{"Uldaman", "Shrike Bat", 7},
{"Uldaman", "Stone Steward", 7},
{"Uldaman", "Stonevault Ambusher", 8},
{"Uldaman", "Stonevault Brawler", 13},
{"Uldaman", "Stonevault Cave Lurker", 4},
{"Uldaman", "Stonevault Flameweaver", 4},
{"Uldaman", "Stonevault Geomancer", 6},
{"Uldaman", "Stonevault Mauler", 6},
{"Uldaman", "Stonevault Oracle", 22},
{"Uldaman", "Stonevault Pillager", 13},
{"Zul'Farrak", "Murta Grimgut", 1},
{"Zul'Farrak", "Oro Eyegouge", 1},
{"Zul'Farrak", "Raven", 1},
{"Zul'Farrak", "Sandfury Acolyte", 2},
{"Zul'Farrak", "Sandfury Blood Drinker", 47},
{"Zul'Farrak", "Sandfury Cretin", 3},
{"Zul'Farrak", "Sandfury Drudge", 16},
{"Zul'Farrak", "Sandfury Guardian", 4},
{"Zul'Farrak", "Sandfury Shadowcaster", 18},
{"Zul'Farrak", "Sandfury Shadowhunter", 30},
{"Zul'Farrak", "Sandfury Witch Doctor", 46},
{"Zul'Farrak", "Sergeant Bly", 1},
{"Zul'Farrak", "Servant of Antu'sul", 1},
{"Zul'Farrak", "Sul'lithuz Sandcrawler", 15},
{"Zul'Farrak", "Zul'Farrak Zombie", 1},
{"Sunken Temple", "Atal'ai Corpse Eater", 3},
{"Sunken Temple", "Atal'ai Deathwalker", 9},
{"Sunken Temple", "Atal'ai Deathwalker's Spirit", 9},
{"Sunken Temple", "Atal'ai High Priest", 3},
{"Sunken Temple", "Hakkari Frostwing", 2},
{"Sunken Temple", "Hakkari Sapper", 4},
{"Sunken Temple", "Nightmare Scalebane", 8},
{"Sunken Temple", "Nightmare Wanderer", 4},
{"Sunken Temple", "Nightmare Wyrmkin", 6},
{"Sunken Temple", "Weaver", 1},
{"Sunken Temple", "Dreamscythe", 1},
{"Sunken Temple", "Morphaz", 1},
{"Sunken Temple", "Hazzas", 1},
{"Maraudon", "Barbed Lasher", 1},
{"Maraudon", "Cavern Lurker", 1},
{"Maraudon", "Cavern Shambler", 1},
{"Maraudon", "Celebras the Redeemed", 1},
{"Maraudon", "Celebrian Dryad", 1},
{"Maraudon", "Constrictor Vine", 1},
{"Maraudon", "Creeping Sludge", 1},
{"Maraudon", "Deeprot Stomper", 1},
{"Maraudon", "Deeprot Tangler", 1},
{"Maraudon", "Noxious Slime", 1},
{"Maraudon", "Primordial Behemoth", 1},
{"Maraudon", "Putridus Satyr", 1},
{"Maraudon", "Putridus Shadowstalker", 1},
{"Maraudon", "Putridus Trickster", 1},
{"Maraudon", "Sister of Celebras", 1},
{"Maraudon", "Spewed Larva", 1},
{"Maraudon", "Subterranean Diemetradon", 1},
{"Maraudon", "Theradrim Guardian", 1},
{"Maraudon", "Theradrim Shardling", 1},
{"Maraudon", "Thessala Hydra", 1},
{"Blackrock Depths", "Anvilrage Captain", 1},
{"Blackrock Depths", "Anvilrage Footman", 1},
{"Blackrock Depths", "Anvilrage Guardsman", 1},
{"Blackrock Depths", "Anvilrage Marshal", 1},
{"Blackrock Depths", "Anvilrage Medic", 1},
{"Blackrock Depths", "Anvilrage Officer", 1},
{"Blackrock Depths", "Anvilrage Overseer", 1},
{"Blackrock Depths", "Anvilrage Soldier", 1},
{"Blackrock Depths", "Anvilrage Warden", 1},
{"Blackrock Depths", "Blackbreath Crony", 1},
{"Blackrock Depths", "Blazing Fireguard", 1},
{"Blackrock Depths", "Dark Guard", 1},
{"Blackrock Depths", "Doomforge Dragoon", 1},
{"Blackrock Depths", "Fireguard", 1},
{"Blackrock Depths", "Fireguard Destroyer", 1},
{"Blackrock Depths", "High Justice Grimstone", 1},
{"Blackrock Depths", "Korv", 1},
{"Blackrock Depths", "Lefty", 1},
{"Blackrock Depths", "Malgen Longspear", 1},
{"Blackrock Depths", "Molten War Golem", 1},
{"Blackrock Depths", "Ragereaver Golem", 1},
{"Blackrock Depths", "Ribbly's Crony", 1},
{"Blackrock Depths", "Rotfang", 1},
{"Blackrock Depths", "Snokh Blackspine", 1},
{"Blackrock Depths", "Twilight Bodyguard", 1},
{"Blackrock Depths", "Twilight Emissary", 1},
{"Blackrock Depths", "Twilight's Hammer Torturer", 1},
{"Blackrock Depths", "Ursula Direbrew", 1},
{"Blackrock Depths", "Warbringer Construct", 1},
{"Blackrock Depths", "Wrath Hammer Construct", 1},
{"Blackrock Spire", "Bloodaxe Evoker", 1},
{"Blackrock Spire", "Bloodaxe Raider", 1},
{"Blackrock Spire", "Bloodaxe Summoner", 1},
{"Blackrock Spire", "Bloodaxe Veteran", 1},
{"Blackrock Spire", "Bloodaxe Warmonger", 1},
{"Blackrock Spire", "Firebrand Darkweaver", 1},
{"Blackrock Spire", "Firebrand Dreadweaver", 1},
{"Blackrock Spire", "Firebrand Grunt", 1},
{"Blackrock Spire", "Firebrand Invoker", 1},
{"Blackrock Spire", "Firebrand Legionnaire", 1},
{"Blackrock Spire", "Firebrand Pyromancer", 1},
{"Blackrock Spire", "Scarshield Acolyte", 1},
{"Blackrock Spire", "Scarshield Legionnaire", 1},
{"Blackrock Spire", "Scarshield Raider", 1},
{"Blackrock Spire", "Scarshield Spellbinder", 1},
{"Blackrock Spire", "Scarshield Warlock", 1},
{"Blackrock Spire", "Smolderthorn Axe Thrower", 1},
{"Blackrock Spire", "Smolderthorn Berserker", 1},
{"Blackrock Spire", "Smolderthorn Headhunter", 1},
{"Blackrock Spire", "Smolderthorn Mystic", 1},
{"Blackrock Spire", "Smolderthorn Seer", 1},
{"Blackrock Spire", "Smolderthorn Shadow Hunter", 1},
{"Blackrock Spire", "Smolderthorn Shadow Priest", 1},
{"Blackrock Spire", "Smolderthorn Witch Doctor", 1},
{"Blackrock Spire", "Spire Spider", 1},
{"Blackrock Spire", "Spirestone Battle Mage", 1},
{"Blackrock Spire", "Spirestone Enforcer", 1},
{"Blackrock Spire", "Spirestone Mystic", 1},
{"Blackrock Spire", "Spirestone Ogre Magus", 1},
{"Blackrock Spire", "Spirestone Reaver", 1},
{"Blackrock Spire", "Spirestone Warlord", 1},
{"Blackrock Spire", "Urok Enforcer", 1},
{"Blackrock Spire", "Urok Ogre Magus", 1},
{"Dire Maul", "Arcane Aberration", 1},
{"Dire Maul", "Arcane Torrent", 1},
{"Dire Maul", "Death Lash", 1},
{"Dire Maul", "Eldreth Apparition", 1},
{"Dire Maul", "Eldreth Darter", 1},
{"Dire Maul", "Eldreth Phantasm", 1},
{"Dire Maul", "Eldreth Seether", 1},
{"Dire Maul", "Eldreth Sorcerer", 1},
{"Dire Maul", "Eldreth Spectre", 1},
{"Dire Maul", "Eldreth Spirit", 1},
{"Dire Maul", "Fel Lash", 1},
{"Dire Maul", "Gordok Brute", 1},
{"Dire Maul", "Gordok Bushwacker", 1},
{"Dire Maul", "Gordok Captain", 1},
{"Dire Maul", "Gordok Mage-Lord", 1},
{"Dire Maul", "Gordok Reaver", 1},
{"Dire Maul", "Gordok Spirit", 1},
{"Dire Maul", "Gordok Warlock", 1},
{"Dire Maul", "Ironbark Protector", 1},
{"Dire Maul", "Mana Remnant", 1},
{"Dire Maul", "Netherwalker", 1},
{"Dire Maul", "Petrified Guardian", 1},
{"Dire Maul", "Petrified Treant", 1},
{"Dire Maul", "Residual Monstrosity", 1},
{"Dire Maul", "Warpwood Crusher", 1},
{"Dire Maul", "Warpwood Guardian", 1},
{"Dire Maul", "Warpwood Stomper", 1},
{"Dire Maul", "Warpwood Tangler", 1},
{"Dire Maul", "Warpwood Treant", 1},
{"Dire Maul", "Wilspawn Betrayer", 1},
{"Dire Maul", "Wilspawn Felsworn", 1},
{"Dire Maul", "Wilspawn Hellcaller", 1},
{"Dire Maul", "Wilspawn Rogue", 1},
{"Dire Maul", "Wilspawn Satyr", 1},
{"Dire Maul", "Wilspawn Shadowstalker", 1},
{"Dire Maul", "Wilspawn Trickster", 1},
{"Dire Maul", "Xorothian Dreadsteed", 1},
{"Pit of Saron", "Alliance Slave", 2},
{"Pit of Saron", "Coliseum Champion", 16},
{"Pit of Saron", "Deathwhisper Necrolyte", 7},
{"Pit of Saron", "Deathwhisper Shadowcaster", 4},
{"Pit of Saron", "Deathwhisper Torturer", 4},
{"Pit of Saron", "Fallen Warrior", 14},
{"Pit of Saron", "Geist Ambusher", 5},
{"Pit of Saron", "Horde Slave", 2},
{"Pit of Saron", "Hungering Ghoul", 8},
{"Pit of Saron", "Iceborn Proto-Drake", 2},
{"Pit of Saron", "Plagueborn Horror", 5},
{"Pit of Saron", "Stonespine Gargoyle", 2},
{"Pit of Saron", "Wrathbone Coldwraith", 4},
{"Pit of Saron", "Wrathbone Laborer", 14},
{"Pit of Saron", "Wrathbone Skeleton", 12},
{"Pit of Saron", "Ymirjar Deathbringer", 2},
{"Pit of Saron", "Ymirjar Flamebearer", 4},
{"Pit of Saron", "Ymirjar Skycaller", 2},
{"Pit of Saron", "Ymirjar Wrathbringer", 4},
{"The Forge of Souls", "Soul Horror", 4},
{"The Forge of Souls", "Soulguard Adept", 5},
{"The Forge of Souls", "Soulguard Animator", 8},
{"The Forge of Souls", "Soulguard Bonecaster", 5},
{"The Forge of Souls", "Soulguard Reaper", 6},
{"The Forge of Souls", "Soulguard Watchman", 8},
{"The Forge of Souls", "Spectral Warden", 3},
{"Halls of Reflection", "Ghostly Priest", 7},
{"Halls of Reflection", "Lumbering Abomination", 6},
{"Halls of Reflection", "Phantom Mage", 4},
{"Halls of Reflection", "Risen Witch Doctor", 9},
{"Halls of Reflection", "Shadowy Mercenary", 5},
{"Halls of Reflection", "Tortured Rifleman", 6},
{"The Nexus", "Alliance Berserker", 4},
{"The Nexus", "Alliance Cleric", 5},
{"The Nexus", "Alliance Commander", 1},
{"The Nexus", "Alliance Ranger", 4},
{"The Nexus", "Azure Enforcer", 10},
{"The Nexus", "Azure Magus", 1},
{"The Nexus", "Azure Scale-Binder", 6},
{"The Nexus", "Azure Warder", 3},
{"The Nexus", "Chaotic Rift", 6},
{"The Nexus", "Crazed Mana-Surge", 7},
{"The Nexus", "Crazed Mana-Wraith", 88},
{"The Nexus", "Crystalline Keeper", 11},
{"The Nexus", "Crystalline Protector", 5},
{"The Nexus", "Crystalline Tender", 8},
{"The Nexus", "Grand Magus Telestra", 1},
{"The Nexus", "Mage Hunter Initiate", 7},
{"The Nexus", "Mage Slayer", 6},
{"The Nexus", "Steward", 5},
}
